version: '1'

services:
  db:
    build:
      context: ./docker-mssqldb/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "jcjeancarlo2017"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S db1.internal.prod.jcjeancarlo.com -U SA -P 'jcjeancarlo2017' -Q 'select distinct 1 from AdventureWorksDW2017.dbo.DimDate'
    networks:
      mynetwork:
        aliases:
          - db1.internal.prod.jcjeancarlo.com
  web:
    build:
      context: ./docker-web-nodejs/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.jcjeancarlo.com      
  restapi:
    build:
      context: ./mssql-restapi-nodejs/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      mynetwork:
        aliases:
          - restapi1.internal.prod.jcjeancarlo.com        

networks:
  mynetwork:
    driver: bridge