version: '3'
services:
  db:
    build:
      context: ./docker-mssqldb/
      dockerfile: Dockerfile
    restart: always
    privileged: true      
    ports:
      - "1433:1433"
    volumes:
        - /docker/vol/handson/docker-mssqldb/data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "teste2017"
      TZ: "Brazil/East"
    healthcheck:
      test: sqlcmd -S db1.internal.teste.com -U SA -P teste2017 -i create-db.sql ||
            sqlcmd -S db1.internal.teste.com -U SA -P teste2017 -i create-table.sql
    networks:
      mynetwork:
        aliases:
            - db1.internal.teste.com            
  web:
    build:
      context: ./docker-web-nodejs/
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    restart: unless-stopped
    depends_on:
        - db
    networks:
      mynetwork:
        aliases:
            - web1.internal.teste.com 
  nodeapi:
    build:
      context: ./mssql-restapi-nodejs/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
        - .:/usr/src/app
        - /docker/vol/handson/mssql-restapi-nodejs/node_modules:/usr/src/app/node_modules
    depends_on:
        - db
    healthcheck:
        test: ["CMD", "node", "create-table.js"]
        interval: 1m30s
        timeout: 10s
        retries: 3
    restart: unless-stopped
    networks:
      mynetwork:
        aliases:
            - restapi1.internal.teste.com 
  mongodb:
        image: mongo
        ports:
            - "27017:27017"   
        volumes:
            - /docker/vol/handson/docker-web-mongo/data:/data/db
        networks:
            mynetwork:
                aliases:
                    - mongodb1.internal.teste.com 
  webmongo1:
        build: 
            context: ./docker-web-mongo/
            dockerfile: Dockerfile
        volumes:
            - /docker/vol/handson/docker-web-mongo/online_app:/app
        ports:
            - "3001:3000"
        depends_on:
            - "mongodb"      
        networks:
            mynetwork:
                aliases:
                    - webmongo1.internal.teste.com 

  fateapi:
        build:
            context: ./docker-fate-api/
            dockerfile: Dockerfile
        container_name: FateApp
        ports:
            - "8091:8091"
        volumes:
            - /docker/vol/handson/docker-fate-api/webapps:/volume/fate-api
        depends_on:
            - db            
        networks:
            mynetwork:
                aliases:
                    - fateapi.internal.teste.com
                    
  fateweb:
        build:
            context: ./docker-fate-web/
            dockerfile: Dockerfile
        hostname: fateweb
        container_name: fateweb
        volumes:
         - /docker/vol/handson/docker-fate-web/:/volume/fate-web
        working_dir: /volume/fate-web
        ports:
            - "4200:4200"
        depends_on:
            - db
            - fateapi
        networks:
            mynetwork:
                aliases:
                    - fateapp.internal.teste.com                  
networks:
  mynetwork:
    driver: bridge            