FROM node:10

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY . .

COPY --chown=node:node . .

USER node

EXPOSE 8080

CMD [ "node", "app.js" ]

### para criar a imagem
# docker build -t jcjeancarlo_dockerhub/nodejs-image-demo .

### para construir o container
# docker run --name nodejs-image-demo -p 80:8080 -d jcjeancarlo_dockerhub/nodejs-image-demo 