USE MASTER
GO
USE [master]
GO
CREATE LOGIN [usr_app] WITH PASSWORD=N'usr_app', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE DATABASE [db1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db1', FILENAME = N'/var/opt/mssql/data/db1.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db1_log', FILENAME = N'/var/opt/mssql/data/db1_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [db1] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db1] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db1] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db1] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db1] SET ARITHABORT OFF 
GO
ALTER DATABASE [db1] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db1] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db1] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [db1] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db1] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db1] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db1] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db1] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db1] SET  DISABLE_BROKER 
GO
ALTER DATABASE [db1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db1] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db1] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [db1] SET  READ_WRITE 
GO
ALTER DATABASE [db1] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [db1] SET  MULTI_USER 
GO
ALTER DATABASE [db1] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db1] SET DELAYED_DURABILITY = DISABLED 
GO
USE [db1]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [db1] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
USE [master]
GO
CREATE DATABASE [db2]

USE [db1]
GO
if NOT exists(select top 1 1 from sysusers where name like 'usr_app')
	BEGIN
		CREATE USER [usr_app] FOR LOGIN [usr_app]
		ALTER ROLE [db_owner] ADD MEMBER [usr_app]
	END
ELSE
	BEGIN
		EXEC SP_CHANGE_USERS_LOGIN 'UPDATE_ONE','usr_app','usr_app';
	END
